"""Additional inference experiments for an already-trained Qwen3.5-9B LoRA model.

This script does NOT train the model again.
It reuses the checkpoints produced by:

    train_qwen35_9b_fulltrain_checkpoints_wandb.py

and automatically performs the following three experiments.

Experiment 1
------------
Run the best epoch-1.5 checkpoint again with a larger vision max-pixel budget:

    epoch 1.5 + max_pixels = 768 * 768

Important: max_pixels=768^2 does not blindly resize every image to 768x768.
It raises the processor's maximum allowed image-pixel budget, so sufficiently
large source images can retain more visual detail than with the previous
640^2 cap.

Experiment 2
------------
Soft-vote the same epoch-1.5 checkpoint at two image resolutions:

    50% * probabilities(epoch 1.5, max_pixels=640^2)
  + 50% * probabilities(epoch 1.5, max_pixels=768^2)

The original 640^2 probability CSV from training is reused when available,
so the 640^2 inference normally does not need to run again.

Experiment 3
------------
Interpolate the LoRA *weights themselves* between epoch 1.0 and epoch 1.5,
then run fresh inference at max_pixels=640^2.

Two candidates are created:

    10% * LoRA(epoch 1.0) + 90% * LoRA(epoch 1.5)
    25% * LoRA(epoch 1.0) + 75% * LoRA(epoch 1.5)

This is different from averaging prediction probabilities.  The adapter
parameters are blended first, creating a new LoRA model, and that model is
then used for inference.

Expected project layout
-----------------------
/workspace/ai_challenge/
├── qwen35_9b_extra_inference.py
├── train_qwen35_9b_fulltrain_checkpoints_wandb.py
├── test.csv
├── sample_submission.csv
├── .env
└── outputs/qwen35_9b_fulltrain/
    ├── checkpoints/
    │   ├── epoch_1.0/
    │   │   └── adapter_state.pt
    │   └── epoch_1.5/
    │       └── adapter_state.pt
    └── probabilities/
        └── probabilities_epoch_1.5.csv   # original 640^2 result

Run
---
    source .venv/bin/activate
    python qwen35_9b_extra_inference.py

If 768^2 inference runs out of GPU memory, lower only the inference batch size:

    python qwen35_9b_extra_inference.py --eval-batch-size 2

No optimizer or training state is required.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import torch

try:
    from dotenv import load_dotenv
except ImportError as exc:
    raise RuntimeError(
        "python-dotenv is required. Install it with: pip install -U python-dotenv"
    ) from exc


# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

LABELS = ("a", "b", "c", "d")
PROB_COLUMNS = ("p_a", "p_b", "p_c", "p_d")


# -----------------------------------------------------------------------------
# CLI arguments
# -----------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run extra Qwen3.5-9B inference experiments: 768^2 inference, "
            "640/768 multi-resolution soft voting, and LoRA weight interpolation."
        )
    )

    parser.add_argument("--data-root", type=Path, default=Path("."))
    parser.add_argument("--test-csv", type=str, default="test.csv")
    parser.add_argument(
        "--sample-submission", type=str, default="sample_submission.csv"
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("outputs/qwen35_9b_fulltrain")
    )
    parser.add_argument(
        "--training-script",
        type=str,
        default="train_qwen35_9b_fulltrain_checkpoints_wandb",
        help=(
            "Python module name of the original training script, without .py. "
            "Its dataset/prompt/inference functions are reused so inference is "
            "bit-for-bit consistent with training-time inference logic."
        ),
    )
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    parser.add_argument("--model-id", type=str, default="Qwen/Qwen3.5-9B")

    # The model was trained with min_pixels=256^2 and max_pixels=640^2.
    # We keep the minimum unchanged and vary only the maximum at inference.
    parser.add_argument("--min-pixels", type=int, default=256 * 256)
    parser.add_argument("--baseline-max-pixels", type=int, default=640 * 640)
    parser.add_argument("--highres-max-pixels", type=int, default=768 * 768)

    parser.add_argument("--eval-batch-size", type=int, default=4)
    parser.add_argument("--num-workers", type=int, default=2)

    # Checkpoint names match the folders generated by the training script.
    parser.add_argument("--checkpoint-1.0", dest="checkpoint_10", default="epoch_1.0")
    parser.add_argument("--checkpoint-1.5", dest="checkpoint_15", default="epoch_1.5")

    return parser.parse_args()


# -----------------------------------------------------------------------------
# Small utility functions
# -----------------------------------------------------------------------------


def ensure_file(path: Path, description: str) -> None:
    """Raise a clear error before expensive model loading if an input is missing."""

    if not path.is_file():
        raise FileNotFoundError(f"Missing {description}: {path}")



def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)



def save_json(path: Path, value: Any) -> None:
    ensure_dir(path.parent)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )



def predictions_from_probabilities(probabilities: np.ndarray) -> list[str]:
    """Convert [N, 4] a/b/c/d probabilities into answer letters."""

    if probabilities.ndim != 2 or probabilities.shape[1] != len(LABELS):
        raise ValueError(
            f"Expected probability shape [N, 4], got {probabilities.shape}"
        )

    indices = probabilities.argmax(axis=1)
    return [LABELS[int(index)] for index in indices]



def read_probability_csv(path: Path) -> tuple[list[str], np.ndarray]:
    """Read one of the probability CSV files made by the training script."""

    ensure_file(path, "probability CSV")
    frame = pd.read_csv(path)

    required = {"id", *PROB_COLUMNS}
    missing = sorted(required - set(frame.columns))
    if missing:
        raise ValueError(f"{path} is missing columns: {missing}")

    ids = frame["id"].astype(str).tolist()
    if len(ids) != len(set(ids)):
        raise ValueError(f"{path} contains duplicated IDs")

    probabilities = frame[list(PROB_COLUMNS)].to_numpy(dtype=np.float64)
    return ids, probabilities



def align_probabilities(
    reference_ids: list[str],
    source_ids: list[str],
    source_probabilities: np.ndarray,
) -> np.ndarray:
    """Reorder source probabilities to exactly match reference_ids.

    Although all inference runs should naturally use the same test order, doing
    this alignment by ID prevents a silent ensemble error if a CSV was reordered.
    """

    if len(source_ids) != len(source_probabilities):
        raise ValueError("source ID count and probability row count differ")

    index = {str(item_id): row for row, item_id in enumerate(source_ids)}

    missing = [item_id for item_id in reference_ids if str(item_id) not in index]
    if missing:
        raise ValueError(
            "Probability files do not contain the same IDs. "
            f"Missing examples: {missing[:5]}"
        )

    order = [index[str(item_id)] for item_id in reference_ids]
    return source_probabilities[order]


# -----------------------------------------------------------------------------
# Model / processor loading
# -----------------------------------------------------------------------------


def load_processor(model_id: str, min_pixels: int, max_pixels: int) -> Any:
    """Load a Qwen processor with a chosen inference vision-pixel budget."""

    # Delayed import is intentional. .env (including HF_HOME/HF_TOKEN) is loaded
    # before Transformers/Hugging Face libraries are imported.
    from transformers import AutoProcessor

    print(
        f"Loading processor: {model_id} "
        f"(min_pixels={min_pixels:,}, max_pixels={max_pixels:,})"
    )

    processor = AutoProcessor.from_pretrained(
        model_id,
        min_pixels=min_pixels,
        max_pixels=max_pixels,
        trust_remote_code=True,
    )

    # The original training/inference code uses left padding for inference.
    processor.tokenizer.padding_side = "left"
    if processor.tokenizer.pad_token_id is None:
        processor.tokenizer.pad_token = processor.tokenizer.eos_token

    return processor



def load_base_plus_adapter(model_id: str, checkpoint_dir: Path) -> Any:
    """Load the BF16 base model and attach the epoch-1.5 PEFT/LoRA adapter.

    We start from the epoch-1.5 adapter because it has the exact PEFT config
    (rank, alpha, target modules, etc.) used during training.  Later, for the
    weight-interpolation experiments, only the adapter tensor values are replaced.
    """

    from peft import PeftModel
    from transformers import AutoModelForMultimodalLM

    ensure_file(checkpoint_dir / "adapter_config.json", "adapter config")

    print(f"Loading BF16 base model: {model_id}")
    base_model = AutoModelForMultimodalLM.from_pretrained(
        model_id,
        dtype=torch.bfloat16,
        device_map={"": 0},
        low_cpu_mem_usage=True,
        trust_remote_code=True,
        attn_implementation="sdpa",
    )

    print(f"Attaching PEFT adapter config/weights from: {checkpoint_dir}")
    model = PeftModel.from_pretrained(
        base_model,
        checkpoint_dir,
        is_trainable=False,
    )

    model.eval()
    model.config.use_cache = True
    return model


# -----------------------------------------------------------------------------
# Inference wrapper
# -----------------------------------------------------------------------------


def run_inference(
    *,
    trainlib: Any,
    model: Any,
    processor: Any,
    test_df: pd.DataFrame,
    data_root: Path,
    sample_path: Path,
    eval_batch_size: int,
    num_workers: int,
    description: str,
    probability_path: Path,
    submission_path: Path,
) -> tuple[list[str], np.ndarray, list[str]]:
    """Run one complete test inference and save both probabilities and submission."""

    dataset = trainlib.VQADataset(test_df, data_root, has_answer=False)
    loader = trainlib.build_dataloader(
        dataset,
        processor,
        train=False,
        batch_size=eval_batch_size,
        num_workers=num_workers,
    )

    started = time.time()
    ids, probabilities, predictions = trainlib.predict_choice_probabilities(
        model=model,
        processor=processor,
        loader=loader,
        device=torch.device("cuda:0"),
        description=description,
    )
    elapsed_minutes = (time.time() - started) / 60

    ensure_dir(probability_path.parent)
    ensure_dir(submission_path.parent)

    trainlib.save_probability_frame(
        probability_path,
        ids,
        probabilities,
        predictions,
    )

    submission = trainlib.build_submission_frame(
        ids,
        predictions,
        sample_path,
    )
    submission.to_csv(submission_path, index=False, encoding="utf-8-sig")

    print(f"Saved probabilities : {probability_path}")
    print(f"Saved submission    : {submission_path}")
    print(f"Inference time      : {elapsed_minutes:.1f} min")

    # Explicitly release DataLoader workers/resources before the next experiment.
    del loader, dataset
    torch.cuda.empty_cache()

    return ids, probabilities, predictions


# -----------------------------------------------------------------------------
# LoRA weight interpolation
# -----------------------------------------------------------------------------


def interpolate_adapter_states(
    state_a: dict[str, torch.Tensor],
    state_b: dict[str, torch.Tensor],
    weight_a: float,
    weight_b: float,
) -> dict[str, torch.Tensor]:
    """Linearly interpolate two PEFT adapter state dictionaries on CPU.

    Formula:
        W_new = weight_a * W_a + weight_b * W_b

    The supplied weights are normalized automatically, so (10, 90) and
    (0.1, 0.9) are equivalent.

    This creates a *new adapter parameter point*.  It should not be confused
    with probability soft voting, which combines model outputs after inference.

    Because epoch 1.0 and epoch 1.5 come from the same continuous training run,
    their LoRA parameter keys/shapes should match exactly.  The script checks
    this before blending to avoid silently creating an invalid adapter.
    """

    total = float(weight_a + weight_b)
    if total <= 0:
        raise ValueError("Interpolation weights must sum to a positive number")

    alpha = float(weight_a) / total
    beta = float(weight_b) / total

    keys_a = set(state_a)
    keys_b = set(state_b)
    if keys_a != keys_b:
        only_a = sorted(keys_a - keys_b)[:5]
        only_b = sorted(keys_b - keys_a)[:5]
        raise ValueError(
            "Adapter state keys differ between checkpoints. "
            f"Only in A: {only_a}; only in B: {only_b}"
        )

    mixed: dict[str, torch.Tensor] = {}

    for key in state_a:
        tensor_a = state_a[key]
        tensor_b = state_b[key]

        if tensor_a.shape != tensor_b.shape:
            raise ValueError(
                f"Shape mismatch for {key}: {tensor_a.shape} vs {tensor_b.shape}"
            )

        if torch.is_floating_point(tensor_a) and torch.is_floating_point(tensor_b):
            # Interpolate in float32 on CPU for numerical stability, then cast
            # back to the original adapter dtype expected by PEFT.
            blended = (
                tensor_a.float() * alpha
                + tensor_b.float() * beta
            ).to(dtype=tensor_b.dtype)
            mixed[key] = blended
        else:
            # LoRA states are normally floating tensors.  For any unexpected
            # non-floating tensor, interpolation is undefined; require equality.
            if not torch.equal(tensor_a, tensor_b):
                raise ValueError(
                    f"Non-floating adapter tensor differs between checkpoints: {key}"
                )
            mixed[key] = tensor_b.clone()

    return mixed


def apply_adapter_state(model: Any, state: dict[str, torch.Tensor]) -> None:
    """Replace the currently loaded PEFT adapter tensors with a supplied state."""

    from peft import set_peft_model_state_dict

    result = set_peft_model_state_dict(model, state)
    unexpected = getattr(result, "unexpected_keys", None)
    if unexpected:
        raise RuntimeError(f"Unexpected PEFT keys while applying state: {unexpected}")

    model.eval()
    model.config.use_cache = True
    torch.cuda.empty_cache()


# -----------------------------------------------------------------------------
# Main workflow
# -----------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    args.data_root = args.data_root.resolve()
    args.output_dir = args.output_dir.resolve()
    args.env_file = args.env_file.resolve()

    # Load environment variables before importing Transformers/HF Hub.
    # This matters if .env contains HF_HOME, HF_HUB_CACHE, HF_XET_CACHE or HF_TOKEN.
    load_dotenv(args.env_file, override=False)

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA GPU is required")
    if not torch.cuda.is_bf16_supported():
        raise RuntimeError("A BF16-capable GPU is required")

    gpu_name = torch.cuda.get_device_name(0)
    total_vram = torch.cuda.get_device_properties(0).total_memory / 2**30
    print(f"GPU: {gpu_name} ({total_vram:.1f} GiB)")

    # Reuse the original training module's exact dataset, prompt, collator,
    # probability-scoring, and submission-building code.  This prevents subtle
    # prompt/template differences from making the new inference incomparable.
    try:
        trainlib = importlib.import_module(args.training_script)
    except ImportError as exc:
        raise RuntimeError(
            f"Could not import {args.training_script}.py. "
            "Place this script next to the original training script."
        ) from exc

    checkpoints_root = args.output_dir / "checkpoints"
    checkpoint_10 = checkpoints_root / args.checkpoint_10
    checkpoint_15 = checkpoints_root / args.checkpoint_15

    ensure_file(checkpoint_10 / "adapter_state.pt", "epoch-1.0 adapter state")
    ensure_file(checkpoint_15 / "adapter_state.pt", "epoch-1.5 adapter state")

    test_path = args.data_root / args.test_csv
    sample_path = args.data_root / args.sample_submission
    ensure_file(test_path, "test CSV")
    ensure_file(sample_path, "sample submission CSV")

    test_df = pd.read_csv(test_path)
    trainlib.require_columns(test_df, trainlib.TEST_COLUMNS, str(test_path))

    # Separate directories keep these experimental outputs away from the original
    # training run's submissions/probabilities.
    extra_submissions = args.output_dir / "submissions_extra"
    extra_probabilities = args.output_dir / "probabilities_extra"
    ensure_dir(extra_submissions)
    ensure_dir(extra_probabilities)

    print("\n=== Loading model once for all extra experiments ===")
    model = load_base_plus_adapter(
        args.model_id,
        checkpoint_15,
    )

    # -------------------------------------------------------------------------
    # EXPERIMENT 1: epoch 1.5 at max_pixels=768^2
    # -------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("EXPERIMENT 1: epoch 1.5, high-resolution inference (max 768^2 pixels)")
    print("=" * 80)

    # Ensure the in-memory adapter is exactly epoch 1.5 before inference.
    trainlib.restore_checkpoint(model, checkpoint_15)

    processor_768 = load_processor(
        args.model_id,
        min_pixels=args.min_pixels,
        max_pixels=args.highres_max_pixels,
    )

    prob_768_path = extra_probabilities / "probabilities_epoch_1.5_res768.csv"
    sub_768_path = extra_submissions / "submission_epoch_1.5_res768.csv"

    ids_768, probs_768, _ = run_inference(
        trainlib=trainlib,
        model=model,
        processor=processor_768,
        test_df=test_df,
        data_root=args.data_root,
        sample_path=sample_path,
        eval_batch_size=args.eval_batch_size,
        num_workers=args.num_workers,
        description="epoch 1.5 / max_pixels 768^2",
        probability_path=prob_768_path,
        submission_path=sub_768_path,
    )

    del processor_768
    torch.cuda.empty_cache()

    # -------------------------------------------------------------------------
    # EXPERIMENT 2: multi-resolution 640^2 + 768^2 probability soft voting
    # -------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("EXPERIMENT 2: epoch 1.5 multi-resolution soft voting, 640^2 + 768^2")
    print("=" * 80)

    # The original training script already created this probability CSV using
    # epoch 1.5 with max_pixels=640^2.  Reuse it if it exists to save GPU time.
    original_640_path = (
        args.output_dir / "probabilities" / "probabilities_epoch_1.5.csv"
    )

    if original_640_path.is_file():
        print(f"Reusing existing 640^2 probabilities: {original_640_path}")
        ids_640, probs_640 = read_probability_csv(original_640_path)
    else:
        # Fallback: if the original probability CSV was deleted/moved, reproduce
        # the 640^2 epoch-1.5 inference automatically.
        print("Original 640^2 probabilities not found; rerunning epoch 1.5 at 640^2.")
        trainlib.restore_checkpoint(model, checkpoint_15)
        processor_640 = load_processor(
            args.model_id,
            min_pixels=args.min_pixels,
            max_pixels=args.baseline_max_pixels,
        )

        fallback_prob_path = (
            extra_probabilities / "probabilities_epoch_1.5_res640.csv"
        )
        fallback_sub_path = (
            extra_submissions / "submission_epoch_1.5_res640_reproduced.csv"
        )

        ids_640, probs_640, _ = run_inference(
            trainlib=trainlib,
            model=model,
            processor=processor_640,
            test_df=test_df,
            data_root=args.data_root,
            sample_path=sample_path,
            eval_batch_size=args.eval_batch_size,
            num_workers=args.num_workers,
            description="epoch 1.5 / max_pixels 640^2",
            probability_path=fallback_prob_path,
            submission_path=fallback_sub_path,
        )

        del processor_640
        torch.cuda.empty_cache()

    # Align the 640 probabilities to the newly generated 768 ID order before
    # averaging.  This is safer than assuming the CSV row orders match.
    probs_640_aligned = align_probabilities(ids_768, ids_640, probs_640)

    multi_res_probs = (
        probs_640_aligned.astype(np.float64)
        + probs_768.astype(np.float64)
    ) / 2.0
    multi_res_predictions = predictions_from_probabilities(multi_res_probs)

    multi_prob_path = (
        extra_probabilities / "probabilities_epoch_1.5_res640_768_soft.csv"
    )
    multi_sub_path = (
        extra_submissions / "submission_epoch_1.5_res640_768_soft.csv"
    )

    trainlib.save_probability_frame(
        multi_prob_path,
        ids_768,
        multi_res_probs,
        multi_res_predictions,
    )
    multi_submission = trainlib.build_submission_frame(
        ids_768,
        multi_res_predictions,
        sample_path,
    )
    multi_submission.to_csv(multi_sub_path, index=False, encoding="utf-8-sig")

    print(f"Saved multi-resolution probabilities: {multi_prob_path}")
    print(f"Saved multi-resolution submission   : {multi_sub_path}")

    # Diagnostic: report how many final answers differ from plain 640^2 and 768^2.
    pred_640 = predictions_from_probabilities(probs_640_aligned)
    pred_768 = predictions_from_probabilities(probs_768)
    changed_vs_640 = sum(a != b for a, b in zip(multi_res_predictions, pred_640))
    changed_vs_768 = sum(a != b for a, b in zip(multi_res_predictions, pred_768))
    disagreement_640_768 = sum(a != b for a, b in zip(pred_640, pred_768))

    print(
        f"640 vs 768 disagree on {disagreement_640_768:,}/{len(ids_768):,} questions"
    )
    print(f"Soft vote changes {changed_vs_640:,} answers vs 640^2")
    print(f"Soft vote changes {changed_vs_768:,} answers vs 768^2")

    # -------------------------------------------------------------------------
    # EXPERIMENT 3: LoRA WEIGHT interpolation between epoch 1.0 and 1.5
    # -------------------------------------------------------------------------
    print("\n" + "=" * 80)
    print("EXPERIMENT 3: LoRA weight interpolation, epoch 1.0 <-> epoch 1.5")
    print("=" * 80)

    # Load raw PEFT adapter tensors saved by the training script.  They live on
    # CPU, so blending them requires essentially no GPU memory.
    state_10 = trainlib.load_raw_adapter_state(checkpoint_10 / "adapter_state.pt")
    state_15 = trainlib.load_raw_adapter_state(checkpoint_15 / "adapter_state.pt")

    # Keep interpolation inference at the original 640^2 resolution.  That makes
    # the experiment isolate the effect of adapter-weight interpolation rather
    # than mixing it with the resolution change from Experiments 1/2.
    processor_interp = load_processor(
        args.model_id,
        min_pixels=args.min_pixels,
        max_pixels=args.baseline_max_pixels,
    )

    interpolation_specs = [
        # Mostly preserve the current best epoch-1.5 model while nudging it back
        # toward the less-trained epoch-1.0 point.
        (0.10, 0.90, "w10_90"),
        # A somewhat stronger move toward epoch 1.0.  This may approximate a
        # parameter-space point between the two saved checkpoints, although it
        # is NOT guaranteed to equal the actual trajectory at epoch 1.25/1.4.
        (0.25, 0.75, "w25_75"),
    ]

    interpolation_outputs: list[dict[str, Any]] = []

    for weight_10, weight_15, label in interpolation_specs:
        print(
            f"\nCreating interpolated adapter: "
            f"epoch1.0={weight_10:.0%}, epoch1.5={weight_15:.0%}"
        )

        mixed_state = interpolate_adapter_states(
            state_10,
            state_15,
            weight_a=weight_10,
            weight_b=weight_15,
        )

        # Apply the newly blended LoRA state directly into the already-loaded
        # base model.  This avoids reloading the 19+ GB Qwen base checkpoint.
        apply_adapter_state(model, mixed_state)

        interp_prob_path = (
            extra_probabilities
            / f"probabilities_interp_e1.0_e1.5_{label}_res640.csv"
        )
        interp_sub_path = (
            extra_submissions
            / f"submission_interp_e1.0_e1.5_{label}_res640.csv"
        )

        interp_ids, interp_probs, interp_predictions = run_inference(
            trainlib=trainlib,
            model=model,
            processor=processor_interp,
            test_df=test_df,
            data_root=args.data_root,
            sample_path=sample_path,
            eval_batch_size=args.eval_batch_size,
            num_workers=args.num_workers,
            description=f"LoRA interp e1.0/e1.5 {label} / 640^2",
            probability_path=interp_prob_path,
            submission_path=interp_sub_path,
        )

        interpolation_outputs.append(
            {
                "weights": {"epoch_1.0": weight_10, "epoch_1.5": weight_15},
                "probability_path": str(interp_prob_path),
                "submission_path": str(interp_sub_path),
                "num_predictions": len(interp_ids),
            }
        )

        # mixed_state can be hundreds of MB depending on the LoRA target set.
        # Release its CPU copy before constructing the next interpolation.
        del mixed_state, interp_probs, interp_predictions

    del processor_interp, state_10, state_15
    torch.cuda.empty_cache()

    # -------------------------------------------------------------------------
    # Summary
    # -------------------------------------------------------------------------
    summary = {
        "model_id": args.model_id,
        "gpu": gpu_name,
        "experiment_1_highres": {
            "checkpoint": str(checkpoint_15),
            "max_pixels": args.highres_max_pixels,
            "probability_path": str(prob_768_path),
            "submission_path": str(sub_768_path),
        },
        "experiment_2_multires_soft_vote": {
            "max_pixels": [args.baseline_max_pixels, args.highres_max_pixels],
            "weights": [0.5, 0.5],
            "probability_path": str(multi_prob_path),
            "submission_path": str(multi_sub_path),
            "resolution_prediction_disagreement_count": disagreement_640_768,
            "changed_vs_640_count": changed_vs_640,
            "changed_vs_768_count": changed_vs_768,
        },
        "experiment_3_lora_weight_interpolation": interpolation_outputs,
    }

    summary_path = args.output_dir / "extra_inference_summary.json"
    save_json(summary_path, summary)

    print("\n" + "=" * 80)
    print("ALL EXTRA EXPERIMENTS COMPLETE")
    print("=" * 80)
    print("\nSubmissions created:")
    print(f"  1) {sub_768_path}")
    print(f"  2) {multi_sub_path}")
    for item in interpolation_outputs:
        print(f"  3) {item['submission_path']}")
    print(f"\nSummary: {summary_path}")


if __name__ == "__main__":
    main()
